
x-base-server: &base-server
  restart: unless-stopped
  environment:
    DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    DEBUG: ${DEBUG}
    SECRET_KEY: ${SECRET_KEY}
    ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    TIME_ZONE: ${TIME_ZONE}
    DB_INIT_PASSWORD: ${DB_INIT_PASSWORD}

services:
  server:
    <<: *base-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    command: sh ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - ./media:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - horilla-data-v2:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\" -h 127.0.0.1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  horilla-data-v2:

networks:
  internal:
    driver: bridge
    internal: true
